### ISSUE TITLE
tempo2bpm gives bpm only as int

### ISSUE THREAD

**Issue by richard-vogl** [mido/mido#155]
if the bpm value is not an integer, this causes issues.
was calculating timestamps in seconds for certain midi events, using the tempo of the project. 
when the project had a bpm value with decimals (e.g. 120.5) the events run out of sync, since mido will return a bpm value of 120.

**Comment by heilei** [comment]
I know this is an old issue, but just in case someone else is wondering the same thing... This happens if you run Mido in Python 2: tempo2bpm() uses integer division to calculate the BPM value, and in Python 2, integer division gives an integer result. You need to either switch to Python 3, or fix the code so that the values are converted to floats before division.

**Comment by rdoursenaud** [comment]
We are in the process of dropping Python 2 support so I believe this will become irrelevant.
I'll close the issue for now but feel free to reopen it if need be.
