### ISSUE TITLE
midi channel mismatch 

### ISSUE THREAD

**Issue by leonh** [mido/mido#18]
First off thanks for creating mido.
I'm very much a newbie in terms of controlling midi in python. I've encountered a little problem assigning midi channel for output when testing mido.

my set up is:
mac os x, python3.4, using the rtmidi backend
I'm attempting to send midi data via a midiman midsport 2x2 usb interface to an external sound module (Roland JV-2080)

Using this test code:

import mido

mido.set_backend('mido.backends.rtmidi')
outport = mido.open_output('MIDISPORT 2x2 Port A')
msg = mido.Message('note_on', note=60, velocity=120)
msg.channel = 10
outport.send(msg) 

My problem is: the sound module receives the midi message on channel 11 not channel 10?

**Comment by cjappl** [comment]
I'm not sure if this is worth re-opening, but what would the pros/cons be of moving the channels to 1-16?

I just spent a lot of time hunting down a "bug" in my code, that ended up being this error, JUCE uses 1-16, so when it was sending a message with channel 1, mido was converting it down to 0.

One argument for moving it to 1-16 would be matching the midi standard. I think this better follows the path of "least astonishment" as many programs that use midi will already behave like this, 1==1, 2==2, instead of 0==1, 1==2.

Any thoughts? This would surely break code and require a major version bump.
