### ISSUE TITLE
Bug with MidiFile.length 

### ISSUE THREAD

**Issue by Dertosh** [mido/mido#181]
This will be computed by going through every message in every track and adding up delta times. But time can be in meta message. You can add  `if(not msg.is_meta):` for computing normal playback time.

**Comment by olemb** [comment]
Meta message delta times need to be included to get the correct total playback time. For example the `EndOfTrack` message at the end of a track often has a long delta time to allow played notes to fade out a bit after the end of the song. Without it the track would just end suddently at the last `note_off`.

If playback takes a bit longer than what `MidiFile.length` reports it is because `MIdiFile.play()` doesn't adjust for the time it takes to process each message so it will lag behind a bit more for each message. This has been fixed for the next version of Mido.

It may be that I've misunderstood what you meant, in which case let me know and I'll try to help you.

**Comment by Dertosh** [comment]
Thank you for your explanation. I understand what do you mean. If it doesn't bother you, can you add parameter in this function for getting correct musical measures?

**Comment by rdoursenaud** [comment]
From @olemb comment, I believe this was fixed.
@Dertosh please open another issue if your feature request is still standing. Thanks.
