### ISSUE TITLE
Metadata is very wrong...

### ISSUE THREAD

**Issue by AmitMY** [mido/mido#208]
Both `mido` and `fluidsynth` think a midi file I have is over an hour long
> {"track_name": {"type": "track_name", "name": "Midi recording 38\u0000", "time": 0}, "time_signature": {"type": "time_signature", "numerator": 4, "denominator": 4, "clocks_per_click": 36, "notated_32nd_notes_per_beat": 8, "time": 0}, "end_of_track": {"type": "end_of_track", "time": 0}, "custom": {"tempo": 500000, "total_ticks": 909936, "ticks_per_beat": 96, "length": 4739.250000000001, "readable_length": "Song length: 78 minutes, 59 seconds."}}

However, it is not the case...
If I look in Synthesia, it shows:
![image](https://user-images.githubusercontent.com/5757359/62888987-1ab76680-bd49-11e9-9c6e-6c66068b78c1.png)

If I draw the audio track after converting midi to wav:
![image](https://user-images.githubusercontent.com/5757359/62889045-3cb0e900-bd49-11e9-9b47-008b4d034f55.png)

I suggest you change the "length" in the metadata to be the time of all events, like now, but trim from the end any irrelevant events (not "note playing" events)

**Comment by duhaime** [comment]
Note playing events are not the only relevant events though. There are lots of other event types that are important--pitchwheel, program change, tempo change...

**Comment by AmitMY** [comment]
Are they important despite having no note playing attached to them? Does it matter if the temp changes if no playing follows?

**Comment by duhaime** [comment]
I take your point. Possibly there could be important information in that ending sequence though. Suppose a band were recording some live takes, and a few minutes after a song, they change the voice patch on some instrument. Then they start the next song. You'd want mido to retain those voice changes at the end of a particular midi file even if they weren't sonified, because that would let you stack the midis end to end later and get the proper event sequence.

It's not hard for a user to trim trailing whitespace...

**Comment by olemb** [comment]
I'm sorry to hear you're having problems. Feel free to hit me up on discord any time I'm on. I'm onkole there.
