### ISSUE TITLE
How to handle (synt) parameters that use values >127

### ISSUE THREAD

**Issue by Jee-Bee** [mido/mido#371]
The Introduction
----------------

Currently i'm writing a interface for a [Mopho](https://www.sequential.com/product/mopho/). But i'm running into some problems.
The DSI Mopho makes by default use of NRPN midi messages. Standard CC messages are possible BUT in some cases it don't handle the full parameter bandwidth. There are a limited set of parameters that handle values >127 (up to 254 == -127 to 127 ).
Currently i'm unable to load (No Error) or save (kind of expected error based on #334) Sysex files .

How to replicate
----------------

As an example I add two Sysex files. `Random Stepper` is the first program of the original sound files. `RandomStepper_edit` is a modified version where i changed the filter to 0x80 / 128. This is completely valid value according toe the Mopho manual (max value is 0xa4/163).
1. RandomStepper.syx
2. RandomStepper_edit.syx

the used code is:

```
import os
from pathlib import Path
import mido

filein = "RandomStepper.syx"
# filein = "RandomStepper_edit.syx"
fileout = "test.syx"
path = os.fspath(Path(__file__).resolve().parents[3] / "Downloads/Mopho/Mopho1_2/{}")  # optional

# test open Sysex files
sysex_file = mido.read_syx_file(path.format(filein))

#test modify sysex file
single_message = sysex_file[0]
message_list = list(message_data)
message_list[28] = 163
new_message = mido.Message('sysex', data=message_list)

# test save Sysex files
mido.write_syx_file(path.format(fileout), [new_message])  
```
When i open the file `RandomStepper.syx` it breaks on the line `new_message = mido.Message('sysex', data=message_list)`.
When i open the file `RandomStepper_edit.syx` it breaks on the line `message_list = list(message_data)` because my loaded file is an empty list.

The question
-------------

Based on this what are the best workarounds / methods to handle files that use the full byte as range of values?
For me another (
[RandomStepper_edit.syx.txt](https://github.com/mido/mido/files/8597794/RandomStepper_edit.syx.txt)
[RandomStepper.syx.txt](https://github.com/mido/mido/files/8597795/RandomStepper.syx.txt)
better suited) library is also an option

References
-----------

- The Mopho Manual (With his midi specification) can be found[here](https://www.sequential.com/downloads/mopho/doc/Mopho_Manual_v.1.2.pdf)
- If you want you can download the full set of sounds [here](https://www.sequential.com/mopho-factory-sounds/).
- The Mopho editor can be download [here](https://www.soundtower.com/mopho/)
- [RandomStepper_edit.syx.txt](https://github.com/mido/mido/files/8597794/RandomStepper_edit.syx.txt) (remove the .txt)
- [RandomStepper.syx.txt](https://github.com/mido/mido/files/8597795/RandomStepper.syx.txt) (remove the .txt)

**Comment by rdoursenaud** [comment]
MIDI, [per specification](https://www.midi.org/specifications/midi1-specifications/m1-v4-2-1-midi-1-0-detailed-specification-96-1-4), uses the most significant *bit* to detect whether the current *byte* is Status (MS bit set) or Data (MS bit not set).
Therefore SysEx messages can only contain Data *bytes* which are, by design, 7 *bits* long only allowing 128 values.

To transmit/receive it's internal 8 bit representation (256 values), your synth uses an 8 bit to 7 bits encoding/decoding scheme to pipe these down the MIDI data stream that is described *page 44 of the manual* you kindly provided.

Since this is part of the System Exclusive extension to MIDI, it is your duty to encode/decode these values as needed.
You can't just push illegal values in the MIDI stream expecting it not to break.

**Comment by rdoursenaud** [comment]
Oh and by the way #334 is bogus for the reasons explained above.

**Comment by Jee-Bee** [comment]
My question was about reading, writing from / to file. The question was not about sending the `SysEx` data to a device.
The midi specification don't say anything about file storing as far as i read it...

This is what the Manual say about it (For manual see link original message):

> Packed Data Format
> Data is packed in 8 byte “packets”, with the MS bit stripped from 7 parameter
> bytes, and packed into an eighth byte, which is sent at the start of the 8 byte
> packet.

**Comment by rdoursenaud** [comment]
The same rule applies to storing `SysEx` data which is analogous to the wire protocol.
Your quote from the manual emphases exactly that.

Instead of naively directly modifying a value to anything larger than 7 bits (`0x7F`) you need to do a bit of encoding first to convert your 8 bit value to 7 bits and insert your most significant bit (`MS`) into **another** byte at the correct position.

In summary:
- setting it to 128 (`0x80`) manually as you did will result in a corrupted file that cannot be interpreted
- setting it to 163 (`0xA3`) programmatically will raise a `ValueError` as expected by design

What you should do is:
- Write code that packs values that your Synth support into it's expected `SysEx` format as outlined above

It would look something like this:
```py
"""
Warning: this is untested code written to help you understand.
What should really be done is write a specific parser for that specific SysEx format
and encapsulate that logic into a nice function.
"""

import mido

syx = mido.read_syx_file('RandomStepper.syx')

print(syx[0].data[28])
# 87 (0x57 0b00111001)

# Set to 163 (0xA3 0b10100011)
value = 163
syx[0].data[28] = value & 0x7F  # Set the 7 bits
if value & 0x80:  # MS is set
    last_byte_in_packet = __  # FIXME: find the boundaries of the 8 byte packet and select the last byte
    bit_position = __ # FIXME: find which byte of the 8 byte packet we just modified (A value between 0 and 7)
    syx[0].data[last_byte_in_packet] = syx[0].data[last_byte_in_packet] | (1 << bit_position)  # Set the most significant bit in the 8th byte at the correct position assuming
```

**Comment by rdoursenaud** [comment]
Hope this clears things up for you.
I may sound blunt at times but remember that I'm here to help ;)
