### ISSUE TITLE
SysEx message bytes range should be in 0..255

### ISSUE THREAD

**Issue by mckuhei** [mido/mido#391]

**Comment by rdoursenaud** [comment]
This is out of spec!
What's your use case?

**Comment by mckuhei** [comment]
But I have a midi cannot use mido to open!

**Comment by rdoursenaud** [comment]
Could this be related to #63 ?

Would you be able to share the file by attaching it here? Invalid MIDI files exists.

**Comment by mckuhei** [comment]
[EVANGELION.zip](https://github.com/mido/mido/files/9840152/EVANGELION.zip)

**Comment by rdoursenaud** [comment]
I've opened the file with `debug=True` to see what the problem was.
The issue with this file is not with a SysEx message.
There is some volume change `0xB0 0x07` (CC#7) followed by a value of `0xFF` which is invalid in MIDI. Max permitted value is coded onto 7-bits which is `127` (`0x7F`) (The most significant bit represents a status byte and thus can't be used in a value).

To workaround this, there is a feature in mido to clip invalid values like that to `127`:
```python
from mido import MidiFile
mid = MidiFile('evangelion.mid', clip=True)
```

Please try it.

**Comment by mckuhei** [comment]
Okay thank you
