### ISSUE TITLE
Version string is '0.0.0.dev0'

### ISSUE THREAD

**Issue by olemb** [mido/mido#517]
```
~/src/mido[main]│ python
Python 3.11.2 (main, May 30 2023, 17:45:26) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mido
>>> mido.version.version_info
<Version('0.0.0.dev0')>
>>> 
```

**Comment by rdoursenaud** [comment]
This is the expected behavior when just cloning the repository.

You have to install the package to resolve the version.
See: https://mido.readthedocs.io/en/latest/contributing.html#developers

To elaborate:
The version is now set by `setuptools_scm` which gathers versioning information from GIT when building the package.
I then use `importlib-metadata` to present the version at runtime using introspection.
This means that we don't have to bother editing a file to set a version anymore. Everything is derived from existing metadata.
It's not very KISS but it is very DRY.
If you need to see a local version as a developer, you are required to install the package in [Development Mode (aka Editable)](https://setuptools.pypa.io/en/latest/userguide/development_mode.html) or you will see this bogus version which is the default on purpose.

KISS
: Keep It Simple Stupid
DRY
: Don't Repeat Yourself

**Comment by olemb** [comment]
That makes sense. Thanks!
