### ISSUE TITLE
ValueError: data byte must be in range 0..127

### ISSUE THREAD

**Issue by Cantersoft** [mido/mido#574]
**Describe the bug**
MIDO cannot ingest a particular MIDI file.

**To Reproduce**
1. Attempt to load the attached MIDI file into MIDO.

**Expected behavior**
MIDO ingests the MIDI file as a MidiFile object.

**Code Snippet**
If applicable, add a code snippet to help explain your problem.
```python
import mido
mido.MidiFile("PartyInTheUSA.mid")
```

**Context (please complete the following information):**
- Operating system name & version: Windows 10
- Python version: Python 3.11.4
- mido package version (Retrievable using `mido.version_info`) & installation method (Distribution repository, PyPI, source…): 1.3.2
- backend used (amidi, portmidi, rtmidi, PyGame…): none

**Additional context**
[PartyInTheUSA.zip](https://github.com/mido/mido/files/13932501/PartyInTheUSA.zip)

**Comment by rdoursenaud** [comment]
Hi,

Your MIDI file is probably not specification compliant.
You should be able to open it by passing `clip=True` to the `MIDIFile` constructor.
This clamps all values above 127 to 127 since these are invalid in MIDI:

```py
import mido
MidiFile("PartyInTheUSA.mid", clip=True)
```

This feature is currently undocumented.
Sorry for the inconvenience.
Future mido version will ingest such files leniently and issue a warning instead of raising an error.

Duplicate #525

**Comment by Cantersoft** [comment]
Thanks! Yeah, it'd be cool if that showed a warning or a more specific error message.
